config/routes.rb
Rails.application.routes.draw do
  resources :fileuploads, only:[ :index , :create, :new , :destroy ]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fileuploads_controller.rb
class FileuploadsController < ApplicationController
  def index
    @img_paths = []
    jpgs = Dir.glob(Rails.root.join('public/images', '*'))
    jpgs.each do |png|
      @img_paths.push('/images/'+File.basename(png))
    end
  end

  def create
    uploaded_file = fileupload_param[:file]
    output_path = Rails.root.join('public/images', uploaded_file.original_filename)
    File.open(output_path, 'w+b') do |fp|
      fp.write  uploaded_file.read
    end
    redirect_to action: 'index'	
  end	
  
  private def fileupload_param
    params.require(:fileupload).permit(:file)
  end


  def new
  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fileuploads_helper.rb
module FileuploadsHelper
end

app/views/fileuploads/create.html.erb
<h1>Fileuploads#create</h1>
<p>Find me in app/views/fileuploads/create.html.erb</p>

app/views/fileuploads/destroy.html.erb
<h1>Fileuploads#destroy</h1>
<p>Find me in app/views/fileuploads/destroy.html.erb</p>

app/views/fileuploads/index.html.erb
<h1>Fileuploads#index</h1>
<p>Find me in app/views/fileuploads/index.html.erb</p>


<h1><%= link_to 'Append jpg', new_fileupload_url %></h1>
<% @img_paths.each do |img_path| %>
  <h2> <%= img_path %> </h2>
  <iframe src="<%=img_path%>"  > </iframe>  
  <%= link_to "Link" , img_path %>
<% end %>

app/views/fileuploads/new.html.erb
<h1>Fileuploads#new</h1>
<p>Find me in app/views/fileuploads/new.html.erb</p>

<%= form_tag '/fileuploads', method: 'post', multipart: true do %>
  <label>ファイル</label>
  <%= file_field :fileupload, :file %>
  <%= submit_tag 'Send file' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uploader</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>